package fix

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/nanohype/cloudgov/internal/cloud"
)

// Options controls fix file generation.
type Options struct {
	OutputDir string
	Severity  cloud.Severity
}

// GenerateTerraform writes one .tf file per principal with minimal policy resources.
func GenerateTerraform(findings []cloud.Finding, policies map[string]cloud.Policy, opts Options) error {
	if err := os.MkdirAll(opts.OutputDir, 0o750); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	type entry struct {
		principal cloud.Principal
		policy    cloud.Policy
	}
	seen := make(map[string]entry)
	for _, f := range findings {
		if f.Principal == nil {
			continue
		}
		if cloud.SeverityRank(f.Severity) < cloud.SeverityRank(opts.Severity) {
			continue
		}
		pid := f.Principal.ID
		if _, ok := seen[pid]; !ok {
			seen[pid] = entry{principal: *f.Principal, policy: policies[pid]}
		}
	}

	for _, e := range seen {
		if err := writePrincipalTF(e.principal, e.policy, opts.OutputDir); err != nil {
			return err
		}
	}
	return nil
}

func writePrincipalTF(principal cloud.Principal, policy cloud.Policy, dir string) error {
	s := slug(principal.Name)
	if err := NameComponent("principal", s); err != nil {
		return err
	}
	// Reachable on a valid principal: PathUnder also refuses a name that is
	// already a symlink, which has nothing to do with the check above.
	filename, err := PathUnder(dir, "minimal_"+s+".tf")
	if err != nil {
		return err
	}

	var content string
	switch principal.Provider {
	case "aws":
		content = formatAWSTF(s, principal.Name, policy)
	default:
		content = fmt.Sprintf("# no Terraform template available for provider %q\n", principal.Provider)
	}

	// The error names the principal: `iam fix` writes one file per principal,
	// and the operator's next move is to re-run for the one that failed, which
	// a bare path error does not identify.
	if err := os.WriteFile(filename, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write fix for %s: %w", principal.Name, err)
	}
	return nil
}

func formatAWSTF(s, name string, policy cloud.Policy) string {
	// Emit the policy as a literal JSON string via a heredoc. The previous
	// jsonencode(<raw policy JSON>) form broke two ways: Terraform interpolated IAM
	// policy variables like ${aws:username} (treating them as template expressions
	// -> "Extra characters after interpolation expression"), and it rejected JSON
	// escapes HCL doesn't accept (e.g. \/, \b). A heredoc keeps backslashes literal;
	// escaping ${ and %{ stops the remaining interpolation so policy variables
	// survive verbatim. Pretty-printed so the generated file is reviewable.
	body := "{}"
	if len(policy.Raw) > 0 {
		var buf bytes.Buffer
		if err := json.Indent(&buf, policy.Raw, "", "  "); err == nil {
			body = buf.String()
		} else {
			body = string(policy.Raw)
		}
	}
	body = strings.ReplaceAll(body, "${", "$${")
	body = strings.ReplaceAll(body, "%{", "%%{")
	return fmt.Sprintf(`resource "aws_iam_policy" "minimal_%s" {
  name        = "minimal-%s"
  description = "Minimal policy generated by cloudgov"
  policy      = <<POLICY
%s
POLICY
}
`, s, strings.ReplaceAll(name, "_", "-"), body)
}

// slug renders an arbitrary principal name as one filename element.
//
// The named substitutions are kept so existing filenames do not move, and a
// sweep against what NameComponent accepts is added behind them. A replacer
// alone names the characters someone thought of, and this one had already let a
// backslash and a colon through — a backslash being a separator by this
// package's own definition, and a colon appearing in every principal ARN.
func slug(name string) string {
	// The named substitutions first, so the filenames this produces do not change:
	// "@" carries meaning spelled out, and "." "-" and "/" have always collapsed
	// to an underscore here.
	lowered := strings.NewReplacer(
		"/", "_", "@", "_at_", ".", "_", "-", "_", " ", "_",
	).Replace(strings.ToLower(name))

	// Then everything else outside the accepted set, which is the half a list of
	// substitutions kept missing.
	var b strings.Builder
	b.Grow(len(lowered))
	for _, r := range lowered {
		if allowedInAName(r) {
			b.WriteRune(r)
			continue
		}
		b.WriteRune('_')
	}
	return b.String()
}
