package fix

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/nanohype/cloudgov/internal/cloud"
)

// Options controls fix file generation.
type Options struct {
	OutputDir string
	Severity  cloud.Severity
}

// GenerateTerraform writes one .tf file per principal with minimal policy resources.
func GenerateTerraform(findings []cloud.Finding, policies map[string]cloud.Policy, opts Options) error {
	if err := os.MkdirAll(opts.OutputDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	type entry struct {
		principal cloud.Principal
		policy    cloud.Policy
	}
	seen := make(map[string]entry)
	for _, f := range findings {
		if f.Principal == nil {
			continue
		}
		if cloud.SeverityRank(f.Severity) < cloud.SeverityRank(opts.Severity) {
			continue
		}
		pid := f.Principal.ID
		if _, ok := seen[pid]; !ok {
			seen[pid] = entry{principal: *f.Principal, policy: policies[pid]}
		}
	}

	for _, e := range seen {
		if err := writePrincipalTF(e.principal, e.policy, opts.OutputDir); err != nil {
			return err
		}
	}
	return nil
}

func writePrincipalTF(principal cloud.Principal, policy cloud.Policy, dir string) error {
	s := slug(principal.Name)
	filename := filepath.Join(dir, "minimal_"+s+".tf")

	var content string
	switch principal.Provider {
	case "aws":
		content = formatAWSTF(s, principal.Name, policy)
	default:
		content = fmt.Sprintf("# no Terraform template available for provider %q\n", principal.Provider)
	}

	return os.WriteFile(filename, []byte(content), 0o644)
}

func formatAWSTF(s, name string, policy cloud.Policy) string {
	policyExpr := `jsonencode({})`
	if len(policy.Raw) > 0 {
		policyExpr = "jsonencode(" + string(policy.Raw) + ")"
	}
	return fmt.Sprintf(`resource "aws_iam_policy" "minimal_%s" {
  name        = "minimal-%s"
  description = "Minimal policy generated by cloudgov"
  policy      = %s
}
`, s, strings.ReplaceAll(name, "_", "-"), policyExpr)
}

func slug(name string) string {
	return strings.NewReplacer(
		"/", "_", "@", "_at_", ".", "_", "-", "_", " ", "_",
	).Replace(strings.ToLower(name))
}
